### ISSUE TITLE
Report A Bug link in the header points to wrong repository

### ISSUE THREAD

**Issue by breyana** [GuildCrafts/curriculum#103]
Current Result: 
Report a Bug links to https://github.com/isaacs/github/issues/new?&body=%23+Bug+Report%0A%0AI+found+a+problem+on+http%3A%2F%2Fcurriculum.learnersguild.org%2Fphases%2F1%2F%0A%0A

Expected Result:
Report a Bug links to https://github.com/GuildCrafts/curriculum/issues/new?&body=%23+Bug+Report%0A%0AI+found+a+problem+on+http%3A%2F%2Fcurriculum.learnersguild.org%2Fphases%2F1%2F%0A%0A

**Comment by deadlyicon** [comment]
you'll have to show this to me. Its right everywhere I've checked.

**Comment by deadlyicon** [comment]
@breyana please come show this to me sometime

**Comment by breyana** [comment]
It looks like it's been fixed recently 👍
