### ISSUE TITLE
'P' and 'B' are too close in shape and make looking at modules/benchmark list too confusing

### ISSUE THREAD

**Issue by breyana** [GuildCrafts/curriculum#104]
'P' and 'B' are too close in shape and make looking at modules/benchmark list too confusing; the shapes blend together.

Having the module groups separated, or adding in emojis again, would help visually differentiating the practice modules from the benchmarks more easily.  

I'm unsure of the best solution, or why the emojis were removed in the first place.

**Comment by jrpool** [comment]
I agree they are subtly different. Jared says putting checkboxes there so we can check off modules as complete is on the agenda. Meanwhile, symbols like “-” for practice modules and “*” for benchmark modules would be much easier to distinguish without creating any emoji rendering issues.

**Comment by deadlyicon** [comment]
fixed.
