### ISSUE TITLE
minor branding tweaks

### ISSUE THREAD

**Issue by jeffreywescott** [GuildCrafts/curriculum#113]
- in the header, use the color logo rather than the white one (I know the design guidelines say otherwise, but it looks better in color)
- links in the header should be "light grey" from the design guide: #E2E3E4
- fonts: use Stag font for headers and Proxima Nova for body copy (available here: https://github.com/LearnersGuild/learnersguild.github.io/tree/master/fonts)

**Comment by deadlyicon** [comment]
@tannerwelsh wanna take this one?

**Comment by tannerwelsh** [comment]
Sure thing
