### ISSUE TITLE
Checks disappearing on skills list

### ISSUE THREAD

**Issue by sashajustice** [GuildCrafts/curriculum#124]
Sometimes checkoffs disappear from the skills list when a page is changed and you go back to it.

**Comment by deadlyicon** [comment]
there is code to address that issue. can you show it to me?

**Comment by sashajustice** [comment]
toggle..it's not happening anymore!

**Comment by deadlyicon** [comment]
![](https://media.tenor.com/images/8d30c83d76a1563babcd0df4731f29fe/tenor.gif)

**Comment by jrpool** [comment]
It is now happening again.
