### ISSUE TITLE
Changes to install instructions (new node consideration) 

### ISSUE THREAD

**Issue by pllearns** [GuildCrafts/curriculum#126]
Just a quick note that with the new version of node what was once: 

`npm install --save express cookie-parser body-parser`

can now be this: 
`npm install express cookie-parser body-parser`

and `npm install --save-dev nodemon` 

can now be:
`npm install -D nodemon`

I know that many people may be operating off of older node versions, or using nvm in certain scenarios to use an older node, but, as more go to node 8 and npm 5, these instructions will be more commonplace. Please correct any misunderstanding I may have, and since this is not remotely a high-priority item, no worries if this isn't implemented.

**Comment by deadlyicon** [comment]
`--save` is on by default for the new `npm`? I'll probably leave the `--save` just to be explicit
