### ISSUE TITLE
"Report a Bug" link misleading

### ISSUE THREAD

**Issue by jrpool** [GuildCrafts/curriculum#128]
The "Improve This Page" and "Report a Bug" links on curriculum pages are VASTLY different, the former being for the curriculum and the latter being for a private repository aimed at supporting all of Github! The "Report a Bug" link should be removed, or, if it is retained, both relocated and reworded so learners will know what it's about. Otherwise, bug reports from some learners about the curriculum application will continue to get lost.

**Comment by deadlyicon** [comment]
fixed
