### ISSUE TITLE
Dot Files Exercise Terminal Error

### ISSUE THREAD

**Issue by jcelder** [GuildCrafts/curriculum#200]
# Bug Report

There seem's to be an issue with Line 59 of the .bash_profile file included as part of the Dot Files exercise error. After moving and renaming files to the home directory and starting a new terminal process the following error pops up:
`-bash: unalias: git: not found`

Line 59 reads:
`export PS1=' \[\033[4;1;${PROMPT_COLOR}m\]\w\[\033[0m\]$(unalias git; __git_ps1 " $(git config --get user.email) (%s)") \n$ '`

Removing the unalias git portion of the line seems to correct the error.
`export PS1=' \[\033[4;1;${PROMPT_COLOR}m\]\w\[\033[0m\]$( __git_ps1 " $(git config --get user.email) (%s)") \n$ '`

**Comment by deadlyicon** [comment]
fixed. Thanks!
