### ISSUE TITLE
curriculum app branding is off

### ISSUE THREAD

**Issue by jeffreywescott** [GuildCrafts/curriculum#74]
From [ch3403](https://app.clubhouse.io/learnersguild/story/3403)

### colors

We need to ensure that the branding (colors, mostly) align with the Guild branding guide.

### favicon

We should always use the Learners Guild icon for favicons for all services. This was a Q1 goal of "internal brand matching external brand".

**Side-note:** Please don't create new iconography in any of our services!

#### Details

The "right" way to do it (that works on all devices in a seamless way) is to do something like IDM does by downloading the `<head>` metadata as necessary from `brand.learnersguild.org`.

Check out `npm run icons:fetch` on IDM.
### Tasks

- [ ] use standard favicon
- [ ] ensure colors match style guide

**Comment by tannerwelsh** [comment]
merged into #76
