### ISSUE TITLE
Move jsdev content into curriculum

### ISSUE THREAD

**Issue by jeffreywescott** [GuildCrafts/curriculum#77]
From [ch3834](https://app.clubhouse.io/learnersguild/story/3834)

Let's move all the goal data from jsdev into curriculum so that we can decommission jsdev.
### Tasks

- [ ] Make relevant goals visible in curriculum UI
- [ ] Re-create goal API from curriculum service for consumption by Echo

**Comment by punitrathore** [comment]
@deadlyicon yes, this is fixed in #83
